### ISSUE TITLE
Sony sync data not coming into resolve with 1.2.1

### ISSUE THREAD

**Issue by dizzybro** [gyroflow/gyroflow-ofx#39]
When bringing in a project using my Sony FX30, the footage is auto-synced and stable in Gyroflow, but in Resolve it results in shaky non-synced footage. I can add a manual sync in Gyroflow and everything is stable in Resolve (but now becomes shaky in the Gyroflow UI). Everything is smooth and synced with OFX 1.2 (with both Gyroflow 1.5.1 and 1.5.2).

**Comment by AdrianEddy** [comment]
ugh, you're right, my bad! Fixed in v1.2.2

**Comment by dizzybro** [comment]
Awesome, thanks. I also noticed that I get an FPS mismatch in Resolve when
using 59.94FPS footage on a 29.97 timeline. Looking back, a previous
version of the plugin said it addressed this, but I still get the error.
Not sure if this is expected and I'm just misinterpreting something or not.
With matching FPS I don't even need to launch Gyroflow, I can achieve
stabilization in the OFX plugin, but with footage that is double my
timeline framerate, it almost looks like the rolling shutter isn't being
accounted for. If I click "open in Gyroflow" and then simply export my
project and open it back in Resolve, everything looks good (although the
mismatch error is still displayed). Just wondering if this is expected
behavior or not.

Thanks again,
Anthony
