### ISSUE TITLE
Interest in VEGAS Pro OFx plugin

### ISSUE THREAD

**Issue by rsmith02ct** [gyroflow/gyroflow-ofx#43]
"Adding BGR support and Vegas' preview scaling is too much work and since there's not enough interest, I won't be working on it"

I am a VEGAS Pro user and I think there is interest in it and have seen a user request to add support for gyro metadata to the developers. Perhaps the developers could provide assistance even in incorporating this into the Fx that come with VEGAS as there is no existing feature like Gyroflow.

In terms of interest I think it is because few of us are aware that Gyroflow exists (so far). There are many Sony users given the history of the software and newer Sonys are incorporating gyro data so I think there is potential.

**Comment by AdrianEddy** [comment]
This affects preview only, the plugin works fine and renders correct videos in Vegas. It's just that the preview has different colors. Just FYI

**Comment by rsmith02ct** [comment]
Thanks for that information.

So far not having much success getting any stabilization to show up in the preview window. Also getting crashes when adjusting parameters like smoothness. I'm using Sony test files from your site to begin with (28mm).

  Problem:             Unmanaged Exception (0xc0000005)
   Fault Module:        C:\Program Files\Common Files\OFX\Plugins\Gyroflow.ofx.bundle\Contents\Win64\Gyroflow.ofx
   Fault Address:       0x00007FFE2D45463A
   Fault Offset:        0x0000000000A4463A

**Comment by AdrianEddy** [comment]
Do you have latest gpu drivers and windows updates?

**Comment by rsmith02ct** [comment]
I'm testing on my laptop at the moment which is an Intel HD 630 iGPU + GTX
1050. The 1050 is on the current studio driver.

Windows version is 10.0.19045 and I don't see updates pending.

If I load the supplied project then there is some evidence of stabilization
working. Modifying smoothness causes consistent crashes (tested with VP
20.411). I sent those to the developer.
I don't see incorrect colors which makes me think I'm missing something.

**Comment by rsmith02ct** [comment]
On my desktop (Intel 13600K with UHD 770GPU and NVIDIA RTX 2080 GPU) I don't have a crash when manipulating smoothness. I do get crashes when changing FOV, playing back, and trying again. 

Is the preview bug that you can't see the effects of settings in real time? I can't seem to see changes in FOV until I close the Fx window. The colors are fine.

**Comment by AdrianEddy** [comment]
please test latest dev build: https://gyroflow.xyz/devbuild/

**Comment by rsmith02ct** [comment]
I tried the dev build with the Sony 1080p 28mm clip. 

It generally seems to work, though after manipulating settings (FOV, smoothness) a few times consistently locks up VEGAS:
 Fault Module:        C:\Program Files\Common Files\OFX\Plugins\Gyroflow.ofx.bundle\Contents\Win64\Gyroflow.ofx
   Fault Address:       0x00007FFFF45512FA
   Fault Offset:        0x00000000009E12FA

There's an issue with preview quality (auto) is selected. Best (auto) and preview (auto) move the image to the upper left corner of the preview window. (full) doesn't have this issue.

**Comment by AdrianEddy** [comment]
Are you sure you replaced the correct files? The preview issue was present in previous build (official v1.2.2) but it's fixed for me in the dev build. It also doesn't crash for me.

**Comment by rsmith02ct** [comment]
I just deleted the OFX subfolder, redownloaded the dev OFX file and pasted
it into the common/OFX folder again (pretty sure I had already done that).
I played with the 28mm clip again for a few minutes (redownloaded it) and
adjusting various settings ended up with a crash shortly thereafter:

   Fault Module:        C:\Program Files\Common
Files\OFX\Plugins\Gyroflow.ofx.bundle\Contents\Win64\Gyroflow.ofx
   Fault Address:       0x00007FF81D1C12FA
   Fault Offset:        0x00000000009E12FA

and again

 Problem:             Unmanaged Exception (0xc0000005)
   Fault Module:        C:\Program Files\Common
Files\OFX\Plugins\Gyroflow.ofx.bundle\Contents\Win64\Gyroflow.ofx
   Fault Address:       0x00007FF81D1C136A
   Fault Offset:        0x00000000009E136A

This is using VEGAS Pro 21 an NVIDIA 1050 (mobile) and i7-7700HQ CPU.

**Comment by AdrianEddy** [comment]
Try this version and let me know if it's any better 
https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-OpenFX-windows.zip

**Comment by rsmith02ct** [comment]
I just had a chance to install it with VP 21.208. 
I added one of the sample media (HD Sony A7III 28mm) and applied this Fx. It crashed immediately with this error.
All the files from the zip do appear to have copied to the common files OFX subfolder.

Problem Description
   Application Name:    VEGAS Pro
   Application Version: Version 21.0 (Build 208)
   Problem:             Unmanaged Exception (0xc00000fd)
   Fault Module:        C:\WINDOWS\SYSTEM32\ntdll.dll
   Fault Address:       0x00007FFBD16ED4E2
   Fault Offset:        0x000000000003D4E2
   
   This is with a laptop with a RTX 4060 GPU.

**Comment by rsmith02ct** [comment]
VP 22 build 122 also hangs after applying the Fx and then crashed (no error message).

**Comment by AdrianEddy** [comment]
> VP 22 build 122 also hangs after applying the Fx and then crashed (no error message).

Should be fixed now https://nightly.link/gyroflow/gyroflow-plugins/workflows/release/main/Gyroflow-OpenFX-windows.zip

**Comment by AdrianEddy** [comment]
Hmm, I tested in Vegas 22 and it works well for me.

What's your hardware? do you have latest GPU drivers installed? Does the main gyroflow app work fine for you and rendering works too? Test the dev build of the app from https://gyroflow.xyz/devbuild/

**Comment by rsmith02ct** [comment]
Thanks for letting me know.

I have an NVIDIA RTX 4060 (mobile) 8GB with the current studio driver
installed. The CPU is an i9-13900H. The integrated GPU driver is the latest
Asus has available (Asus Zenbook).
I can test on a second custom built system for VEGAS later as well as the
main app.

**Comment by rsmith02ct** [comment]
I installed the latest dev build and ran the main app. It does open though
rendering throws an error about keyframes.

In VP 21 it still crashes but in 22 I get to the Ofx menu in VEGAS. Despite
having opened Gyroflow as an admin it can't find the path and I don't see a
way to specify it here.

[image: image.png]

**Comment by AdrianEddy** [comment]
Hmm, this sounds to me like you have some older plugin version installed in some other directory which is read by your VP 21 installation.

The standard path should be: C:\Program Files\Common Files\OFX\Plugins
and Vegas should load it by default without any changes in settings

Double check if you don't have the plugin anywhere else

**Comment by rsmith02ct** [comment]
This is a brand new computer so there are no older plugin versions as far
as I am aware. I just installed VEGAS and Gyroflow.

For testing purposes I deleted the Ofx plugin and then redownloaded it from
the link above and put it back in OFX\plugins.

The plugin is here:
C:\Program Files\Common Files\OFX\Plugins\Gyroflow.ofx.bundle\Contents\Win64

It still crashes VEGAS Pro 21 for some reason.

Problem Description
   Application Name:    VEGAS Pro
   Application Version: Version 21.0 (Build 208)
   Problem:             Unmanaged Exception (0xc00000fd)
   Fault Module:        C:\WINDOWS\SYSTEM32\ntdll.dll
   Fault Address:       0x00007FFE68B8CBBF
   Fault Offset:        0x000000000003CBBF

**Comment by rsmith02ct** [comment]
I had the same instant crash with 21.208 with my desktop (RTX 2080/ 13600K
CPU)

Problem Description
   Application Name:    VEGAS Pro
   Application Version: Version 21.0 (Build 208)
   Problem:             Unmanaged Exception (0xc00000fd)
   Fault Module:        C:\Windows\SYSTEM32\ntdll.dll
   Fault Address:       0x00007FFE6748D685
   Fault Offset:        0x000000000003D685

Fault Process Details
   Process Path:        C:\Program Files\VEGAS\VEGAS Pro 21.0\vegas210.exe
   Process Version:     Version 21.0 (Build 208)
   Process Description: VEGAS Pro
   Process Image Date:  2023-11-29 (Wed Nov 29) 21:19:46
